services:
  db:
    image: postgres:13
    container_name: currencydb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  bot:
    image: node:20.9.0-alpine3.18
    container_name: bot-system
    env_file:
      - .env.dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.pnpm-store
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && npx prisma migrate deploy && pnpm run dev"
    depends_on:
      - db
